[webserver]
port = ":${TILER_SERVER_PORT}"
	[webserver.headers]
	Access-Control-Allow-Origin = "*"

# Tegola offers three tile caching strategies: "file", "redis", and "s3"
[cache]
type = "${TILER_CACHE_TYPE}"
basepath ="${TILER_CACHE_BASEPATH}"
max_zoom = "${TILER_CACHE_MAX_ZOOM}"

bucket = "${TILER_CACHE_BUCKET}"
region = "${TILER_CACHE_REGION}"
aws_access_key_id = "${TILER_CACHE_AWS_ACCESS_KEY_ID}"
aws_secret_access_key = "${TILER_CACHE_AWS_SECRET_ACCESS_KEY}"

#   OpenStreetMap (OSM)
[[providers]]
name = "osm"
type = "postgis"
host = "${POSTGRES_HOST}"
port = 5432
database = "${POSTGRES_DB}"
user = "${POSTGRES_USER}"
password = "${POSTGRES_PASSWORD}"
srid = 3857
max_connections = 40



#	Natural Earth
[[providers]]
name = "ne"
type = "postgis"
host = "${POSTGRES_HOST}"
port = 5432
database = "${POSTGRES_DB}"
user = "${POSTGRES_USER}"
password = "${POSTGRES_PASSWORD}"
srid = 3857
max_connections = 40

	[[providers.layers]]
	name = "ne_110m_populated_places"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, labelrank, name, min_zoom, featurecla, rank_max FROM ne_110m_populated_places WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_populated_places"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, labelrank, name, min_zoom, featurecla, rank_max FROM ne_50m_populated_places WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_populated_places"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, scalerank, labelrank, name, min_zoom, featurecla, rank_max FROM ne_10m_populated_places WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_0_label_points"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, sr_subunit, scalerank FROM ne_10m_admin_0_label_points WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_1_label_points"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, name, scalerank FROM ne_10m_admin_1_label_points WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_110m_admin_0_boundary_lines_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, min_zoom FROM ne_110m_admin_0_boundary_lines_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_admin_0_boundary_lines_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, min_zoom FROM ne_50m_admin_0_boundary_lines_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_0_boundary_lines_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, min_zoom FROM ne_10m_admin_0_boundary_lines_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_admin_0_boundary_lines_disputed_areas"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, min_zoom FROM ne_50m_admin_0_boundary_lines_disputed_areas WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_0_boundary_lines_disputed_areas"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, min_zoom FROM ne_10m_admin_0_boundary_lines_disputed_areas WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_110m_admin_0_countries"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, name_long, abbrev, adm0_a3, min_zoom, min_label, max_label FROM ne_110m_admin_0_countries WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_admin_0_countries"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, name_long, abbrev, adm0_a3, min_zoom, min_label, max_label FROM ne_50m_admin_0_countries WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_0_countries"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, name_long, abbrev, adm0_a3, min_zoom, min_label, max_label FROM ne_10m_admin_0_countries WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_110m_admin_1_states_provinces_lines"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, adm0_name, min_zoom FROM ne_110m_admin_1_states_provinces_lines WHERE wkb_geometry && !BBOX!"

    [[providers.layers]]
	name = "ne_50m_admin_1_states_provinces_lines"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, adm0_name, min_zoom FROM ne_50m_admin_1_states_provinces_lines WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_admin_1_states_provinces_lines"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, adm0_name, min_zoom, min_label FROM ne_10m_admin_1_states_provinces_lines WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_110m_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, min_zoom FROM ne_110m_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, min_zoom FROM ne_50m_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_land"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, min_zoom FROM ne_10m_land WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_50m_admin_1_states_provinces_lakes"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, postal, min_zoom, min_label FROM ne_50m_admin_1_states_provinces_lakes WHERE wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_roads_3"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, name, min_zoom, min_label, type, label FROM ne_10m_roads WHERE min_zoom < 5 AND type <> 'Ferry Route' AND wkb_geometry && !BBOX!"

	[[providers.layers]]
	name = "ne_10m_roads_5"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, name, min_zoom, min_label, type, label FROM ne_10m_roads WHERE min_zoom <= 7  AND type <> 'Ferry Route' AND wkb_geometry && !BBOX!"


[[maps]]
name = "osm"
attribution = "OpenStreetMap" # map attribution
center = [-74.275329586789, -12.153492567373, 8.0] # optional center value. part of the TileJSON spec

	[[maps.layers]]
	name = "populated_places"
	provider_layer = "ne.ne_110m_populated_places"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "populated_places"
	provider_layer = "ne.ne_50m_populated_places"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "populated_places"
	provider_layer = "ne.ne_10m_populated_places"
	min_zoom = 5
	max_zoom = 20

	[[maps.layers]]
	name = "country_lines"
	provider_layer = "ne.ne_110m_admin_0_boundary_lines_land"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "country_lines"
	provider_layer = "ne.ne_50m_admin_0_boundary_lines_land"
	dont_simplify = true
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "country_lines"
	provider_layer = "ne.ne_10m_admin_0_boundary_lines_land"
	min_zoom = 5
	max_zoom = 10

	[[maps.layers]]
	name = "country_lines_disputed"
	provider_layer = "ne.ne_50m_admin_0_boundary_lines_disputed_areas"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "country_lines_disputed"
	provider_layer = "ne.ne_10m_admin_0_boundary_lines_disputed_areas"
	min_zoom = 5
	max_zoom = 10

	[[maps.layers]]
	name = "country_label_points"
	provider_layer = "ne.ne_10m_admin_0_label_points"
	min_zoom = 3
	max_zoom = 20

	[[maps.layers]]
	name = "country_polygons"
	provider_layer = "ne.ne_110m_admin_0_countries"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "country_polygons"
	provider_layer = "ne.ne_50m_admin_0_countries"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "country_polygons"
	provider_layer = "ne.ne_10m_admin_0_countries"
	min_zoom = 5
	max_zoom = 10

	[[maps.layers]]
	name = "state_lines"
	provider_layer = "ne.ne_110m_admin_1_states_provinces_lines"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "state_lines"
	provider_layer = "ne.ne_50m_admin_1_states_provinces_lines"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "state_lines"
	provider_layer = "ne.ne_10m_admin_1_states_provinces_lines"
	min_zoom = 5
	max_zoom = 10

	# Land Polygons
	[[maps.layers]]
	name = "land"
	provider_layer = "ne.ne_110m_land"
	min_zoom = 0
	max_zoom = 2

	[[maps.layers]]
	name = "land"
	provider_layer = "ne.ne_50m_land"
	min_zoom = 3
	max_zoom = 4

	[[maps.layers]]
	name = "land"
	provider_layer = "ne.ne_10m_land"
	min_zoom = 5
	max_zoom = 7
